name: Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter (dev version)
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.34.0-0.0.pre --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          export PATH="$GITHUB_WORKSPACE/flutter/bin:$PATH"
          flutter doctor
      - name: Install dependencies
        run: flutter pub get

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-key.jks" >> android/key.properties
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/upload-key.jks
      - name: Build appBundle
        run: flutter build appbundle
       
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ github.run_number }}
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload .aab to Production Track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: pl.bator.tatry_kamera
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: alpha
          status: completed
